# Generated by Django 4.2.9 on 2024-01-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennzeichen', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('vorname', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField()),
                ('vin', models.CharField(max_length=200)),
                ('firma', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autos', to='user.model')),
            ],
        ),
    ]
