# Generated by Django 4.2.9 on 2024-01-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_autos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autos',
            new_name='Auto',
        ),
    ]
