# Generated by Django 4.2.9 on 2024-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='fahrz',
            field=models.IntegerField(null=True),
        ),
    ]
