# Generated by Django 4.2.9 on 2024-01-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='hersteller',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
