# Generated by Django 4.2.9 on 2024-01-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_auto_kennzeichen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='kilometerstand',
            field=models.IntegerField(null=True),
        ),
    ]
