# Generated by Django 4.2.9 on 2024-01-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_autoimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoimage',
            old_name='image_id',
            new_name='model',
        ),
    ]
