# Generated by Django 4.2.9 on 2024-01-31 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_image_id_autoimage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='user.model'),
        ),
    ]
