# Generated by Django 4.2.9 on 2024-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_autoimage_image_alter_autoimage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
