# Generated by Django 4.2.9 on 2024-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_autoimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
