# Generated by Django 4.2.9 on 2024-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_autoimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/1/'),
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/1/'),
        ),
    ]
