# Generated by Django 4.2.9 on 2024-01-31 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_autoimage_image_alter_autoimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimage',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='user.auto'),
        ),
    ]
