# Generated by Django 4.2.9 on 2024-01-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_autoimage_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoimage',
            name='thumbnail',
        ),
    ]
