# Generated by Django 4.2.9 on 2024-01-31 09:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_autoimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimage',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
