# Generated by Django 4.2.9 on 2024-01-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_autoimage_slot_alter_autoimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoimage',
            old_name='model',
            new_name='auto',
        ),
    ]
