# Generated by Django 4.2.9 on 2024-01-31 13:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_rename_model_autoimage_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimage',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
