# Generated by Django 4.2.9 on 2024-02-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_autoimage_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoimage',
            name='default_image',
        ),
    ]
