# Generated by Django 4.2.9 on 2024-02-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_autoimage_default_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos_seite', models.CharField(max_length=250)),
                ('component_autos_seite', models.CharField(max_length=250)),
                ('element_in_component', models.CharField(max_length=250)),
                ('schaden_descr', models.CharField(max_length=250)),
                ('schaden_value', models.CharField(max_length=250)),
                ('preis', models.IntegerField(max_length=100)),
                ('image_schaden', models.ImageField(blank=True, null=True, upload_to='')),
                ('schaden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bewertungs', to='user.auto')),
            ],
        ),
    ]
