# Generated by Django 4.2.9 on 2024-02-01 14:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_bewertung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='image_schaden',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.schaden_directory_path),
        ),
    ]
