# Generated by Django 4.2.9 on 2024-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_bewertung_image_schaden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='preis',
            field=models.IntegerField(),
        ),
    ]
