# Generated by Django 4.2.9 on 2024-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_bewertung_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='element_in_component',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
