# Generated by Django 4.2.9 on 2024-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_autozubehor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autozubehor',
            name='zusatzInfo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
