# Generated by Django 4.2.9 on 2024-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_autozubehor_zusatzinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autozubehor',
            name='zusatzInfo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
