# Generated by Django 4.2.9 on 2024-02-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_rename_fbaks_autozubehor_fbaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReifen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reifen', models.CharField(max_length=20)),
                ('reifenname', models.CharField(max_length=200)),
                ('profil', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('dot', models.CharField(max_length=100)),
                ('tpms', models.CharField(max_length=100)),
                ('winter', models.CharField(max_length=100)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reifens', to='user.auto')),
            ],
        ),
    ]
