# Generated by Django 4.2.9 on 2024-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_autoreifen_lenspiel_autoreifen_radspiel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autozubehor',
            name='bremse',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
