# Generated by Django 4.2.9 on 2024-02-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_autozubehor_bremse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLackMessung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('kotflügelFS', models.CharField(max_length=50)),
                ('türFS', models.CharField(max_length=50)),
                ('seitenpaneleFS', models.CharField(max_length=50)),
                ('schwellerFS', models.CharField(max_length=50)),
                ('kotflügelBS', models.CharField(max_length=50)),
                ('türBS', models.CharField(max_length=50)),
                ('seitenpaneleBS', models.CharField(max_length=50)),
                ('schwellerBS', models.CharField(max_length=50)),
                ('stosStangeF', models.CharField(max_length=50)),
                ('motorhaubeF', models.CharField(max_length=50)),
                ('heckHeck', models.CharField(max_length=50)),
                ('stosStangeHeck', models.CharField(max_length=50)),
                ('spoilerHeck', models.CharField(max_length=50)),
                ('dach', models.CharField(max_length=50)),
                ('hardTopDach', models.CharField(max_length=50)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messungs', to='user.auto')),
            ],
        ),
    ]
