# Generated by Django 4.2.9 on 2024-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_autolackmessung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolackmessung',
            name='dach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='hardTopDach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='heckHeck',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='kotflügelBS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='kotflügelFS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='motorhaubeF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='schwellerBS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='schwellerFS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='seitenpaneleBS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='seitenpaneleFS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='spoilerHeck',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='stosStangeF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='stosStangeHeck',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='türBS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autolackmessung',
            name='türFS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
