# Generated by Django 4.2.9 on 2024-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_autolackmessung_dach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='fahrz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
