# Generated by Django 4.2.9 on 2024-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_model_fahrz'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
