# Generated by Django 4.2.9 on 2024-02-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_model_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='fahrz',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model',
        ),
    ]
