# Generated by Django 4.2.9 on 2024-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_remove_model_fahrz_remove_model_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='thumbnail',
        ),
    ]
