# Generated by Django 4.2.9 on 2024-02-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_remove_auto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
