# Generated by Django 4.2.9 on 2024-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_auto_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
