# Generated by Django 4.2.9 on 2024-02-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='autoimage',
            name='slug',
        ),
    ]
