# Generated by Django 4.2.9 on 2024-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_remove_auto_slug_remove_autoimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='preis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
