# Generated by Django 4.2.9 on 2024-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_schaden_bewertung_schaden'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='preis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
