# Generated by Django 4.2.9 on 2024-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_preis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='preis',
        ),
    ]
