# Generated by Django 4.2.9 on 2024-02-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_remove_auto_preis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='schaden',
        ),
    ]
