# Generated by Django 4.2.9 on 2024-02-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_auto_schaden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='schaden',
        ),
    ]
