# Generated by Django 4.2.9 on 2024-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_remove_auto_schaden'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewertung',
            name='serviceLeistung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bewertung',
            name='zusatzReparatur',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
