# Generated by Django 4.2.9 on 2024-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_bewertung_serviceleistung_bewertung_zusatzreparatur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='zusatzReparatur',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
