# Generated by Django 4.2.9 on 2024-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_bewertung_behoben'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewertung',
            name='wird_behoben',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
